version: "3.8"

services:
  angular-app:
    image: nginx:alpine
    ports:
      - "4200:80"
    volumes:
      - ./dist/guinea-pig-iframe/browser:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
